# Generated by Django 4.0.6 on 2022-07-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('app_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('endpoints', models.ManyToManyField(related_name='endpoints', to='AuthSystem.endpoint')),
            ],
        ),
        migrations.RemoveField(
            model_name='permissiongroup',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='Endpoints',
        ),
        migrations.DeleteModel(
            name='PermissionGroup',
        ),
        migrations.AddConstraint(
            model_name='endpoint',
            constraint=models.UniqueConstraint(fields=('name', 'app_name', 'class_name'), name='unique_id'),
        ),
    ]
