# Generated by Django 4.0.6 on 2022-07-09 12:23

from django.db import migrations, models
import faino.AuthSystem.models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirm',
            name='code',
            field=models.CharField(blank=True, default=faino.AuthSystem.models.UserConfirm.generate_code, max_length=5, unique=True),
        ),
    ]
