# Generated by Django 4.0.5 on 2022-06-18 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AuthSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirm_user',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
