# Generated by Django 4.0.6 on 2022-07-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthSystem', '0002_alter_userconfirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirm',
            name='code',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='userconfirm',
            name='token',
            field=models.UUIDField(blank=True, unique=True),
        ),
    ]
