version: '3'

services:

  django:
    build:
      dockerfile: ./dockerfile
      args:
        - REQUIREMENTS_FILE=${REQUIREMENTS_FILE}
    depends_on:
      - redis
      - postgres

  redis:
    image: redis:alpine
    restart: always

  postgres:
    image: postgres:alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data:rw

volumes:
  db-data:
