services:

  django:
    volumes:
      - .:/src/:rw
      - statics:/src/static:rw
    env_file:
      - ./config/uvicorn.dev.env
      - ./config/django.dev.env
      - ./config/postgres.dev.env
    entrypoint: [ "bash", "./entrypoint.dev.sh" ]

  postgres:
    env_file:
      - ./config/postgres.dev.env
    volumes:
      - db-data-test:/var/lib/postgresql/data:rw

  nginx:
    env_file:
      - ./config/uvicorn.dev.env
    ports:
      - 8000:80
    volumes:
      - statics:/statics:rw

volumes:
  db-data-test:
  statics:
