services:

  django:
    volumes:
      - .:/src/:rw
      - statics:/src/static:rw
    env_file:
      - ./config/uvicorn.dev.env
      - ./config/django.dev.env
      - ./config/postgres.dev.env
    command:
      - /bin/bash
      - -c
      - |
        python3 manage.py collectstatic --noinput 
        python3 manage.py makemigrations --noinput
        python3 manage.py migrate --noinput
        uvicorn config.asgi:application 
          --reload 
          --host ${DJANGO_IP} 
          --port ${DJANGO_PORT} 
          --workers ${WORKERS_COUNT_UVICORN} 
          ${EXTRA_UVICORN_ARGS}

  postgres:
    env_file:
      - ./config/postgres.dev.env
    volumes:
      - db-data-test:/var/lib/postgresql/data:rw

  nginx:
    env_file:
      - ./config/uvicorn.dev.env
    ports:
      - 8000:80
    volumes:
      - statics:/statics:rw

volumes:
  db-data-test:
  statics:
