# Generated by Django 3.2.6 on 2022-01-11 02:02

import WEB_SERVER.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('name', models.CharField(max_length=62, primary_key=True, serialize=False, unique=True, validators=[WEB_SERVER.models.validator_name])),
            ],
        ),
        migrations.CreateModel(
            name='Source_Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.FloatField(max_length=12)),
                ('source', models.FileField(upload_to='sources')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEB_SERVER.type')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=36)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('password', models.CharField(blank=True, max_length=62)),
                ('mac', models.CharField(blank=True, max_length=17)),
                ('description', models.TextField(blank=True, max_length=600)),
                ('status', models.BooleanField(default=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEB_SERVER.type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Device_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Data_Device', to='WEB_SERVER.device')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ًCS', 'Command Server'), ('CU', 'Command User')], max_length=20)),
                ('data', models.JSONField()),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('time_complated', models.DateTimeField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Command_Device', to='WEB_SERVER.device')),
            ],
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_name', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=80)),
                ('array', models.TextField()),
                ('is_star', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WEB_SERVER.device')),
            ],
        ),
    ]
