# Generated by Django 3.2.6 on 2022-01-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB_SERVER', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='time_complated',
            new_name='time_completed',
        ),
    ]
