######################## BASE PYTHON IMAGE ########################
FROM python:3.9

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 
ENV PORT=8000
ENV IP=0.0.0.0
ENV SETTINGS=settings.settings
ENV REQUIREMENTS=/src/requirements/dev.txt

EXPOSE ${PORT}

WORKDIR /src
COPY . .

RUN pip install --no-cache-dir -r ${REQUIREMENTS}

CMD python3 ./manage.py runserver ${IP}:${PORT} --settings=${SETTINGS}