services:
  django:

    volumes:
      - .:/src/:rw
    env_file:
      - ./dev.env
      - ./uvicorn.dev.env
    command: >
      uvicorn config.asgi:application 
          --reload 
          --host ${DJANGO_IP} 
          --port ${DJANGO_PORT} 
          --workers ${WORKERS_COUNT_UVICORN} 
          ${EXTRA_UVICORN_ARGS}
    ports:
      - "8080:${DJANGO_PORT}"

  postgres:
    env_file:
      - ./.postgres.dev.env
    volumes:
      - db-data-test:/var/lib/postgresql/data:rw

volumes:
  db-data-test:
