services:
  django:

    volumes:
      - .:/src/:rw
    env_file:
      - ./uvicorn.dev.env
      - ./django.dev.env
      - ./postgres.dev.env
    command: >
      uvicorn config.asgi:application 
          --reload 
          --host ${DJANGO_IP} 
          --port ${DJANGO_PORT} 
          --workers ${WORKERS_COUNT_UVICORN} 
          ${EXTRA_UVICORN_ARGS}
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}

  postgres:
    env_file:
      - ./postgres.dev.env
    volumes:
      - db-data-test:/var/lib/postgresql/data:rw

volumes:
  db-data-test:
