# Generated by Django 3.2.5 on 2021-07-11 11:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Demo_webserver_app', '0002_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstatus',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
