# Generated by Django 3.2.5 on 2021-07-11 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Demo_webserver_app', '0003_newstatus_create'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AddField(
            model_name='data',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newstatus',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
